### ISSUE TITLE
珠三角 co-inn 名单接梗

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/PRD#11]
## 珠三角 co-inn 名单接梗

`20150729 11:37 下午 v1.0`

`20150731 10:14 上午 v1.1`

### 背景

[来自珠三角的一吼](https://github.com/OpenMindClub/PRD/issues/9)

**于是乎， 有了 co-inn 的名单**

> 珠三角大区 co-inn 只有四位， 其中 75% 来自开智。 其中 3 位来自于深圳,  1 位福州。
> > co 何须人也 ？
> > > 四好青年
> > > > 爱进步
> > > > 爱分享
> > > > 爱折腾
> > > > 爱学习
> 

> co的三类，根本相通属性是都拥有输出能力的社群小伙伴：
>
1. 创业者：一上来就是奔着创业去的，或者本身就已经在创业。需要的关键支持是类似私人董事会的支持。由导师团提供重大决策建议。面授课程的需求反而没那么密切与大，更多是平时零散沟通以及重大决策支持与方向选择、关键人脉建议支持。
2. 工程师&产品经理&设计师：构成一个好的项目的骨干人才。本身不一定想创业或者短期内达不到创业的水准。通过元学科课程体系，获得思维的提升与技能修炼，让职业生涯发展水准达到一个更高水准。这是这类人的需求。对零散沟通要求不多，平时群内灌水即可，无需太多重大决策支持，更多是需要系统课程。日常讲座搭配开智学院系统课程即可。
3. 独立创作者：这类人天性自由，有极强的通过独立创作谋生的能力或者潜在天赋。一般保持两个身份即可，一个身份是获得正常薪资与医保福利；另一个身份是独立创作者，通过小说、剧本、独立讲课等谋生。对课程需要的支持更多是体系支持与关键人脉支持。建立一套良好的体系，让其小说出版更快、获得收益更大，衍伸版权交易更多，无需自己花太多时间去营销自己，借助整个开智体系来完成营销即可；同时在媒体文化领域引荐关键人脉。课程需求更多在创新方法论、思维训练、创作者生活方式上。
4. 开智社群大区运营者：本身对开智社群认可度极高，基本会成为未来各个大区的运营负责人与未来实体公司管理者。对课程需求更多在于，通过我的范例，获得直接感悟与运营启发。未来直接本地化课程、培训等。

### 分析

跟进珠三角的地域分析， 珠海， 广州， 目测有大妈和珠海热血团坐镇。 已经形成固定的面基氛围。

那么 ……

- 线上的一切最终还是需要线下的转化， 比如 python 班经历， 写作班的面基；
  + python 的小白入手教材还木有
  + 写作班的第一期还木有结束？
     + 问题来了 ？ 价值何在 ？
- 真实的接触， 才有以后良好开始的基础
  + 面基的真正意义是什么？
    + 然后是如何更好的『面』？  
    + 如何让『面』
         + 持续
             + 双规 = 「固定时间」 + 「固定地点」 
         + 产生价值
             + 组织者 + 支撑者 + 参与者 = 共同产生价值 
         + 积累
             + 记录
             + 分享
             + 任何可能的其他形态的转化 
         + 影响  
             + 影响不是要去影响， 而是来自「质量」
                + 用行为去影响，而非宣传  
- 固定的宗教文化， 靠的都是固定时间， 固定低点， 固定召集
  + 面基是个技术活 ？
    + 如何聚集人？
    + 如何让来众获得价值？
    + 如何选地？
    + 如何呈现？
    + 如何普及
    + 如何协作？
    + 标准是啥？
    + 判定是啥？
      + 上面的问题， 或许目前都还是问题 ？
         + 有没有案例可以借鉴
         + 有没有历史可以模仿
         + 有没有现成套路可走？
            + 是借鉴的成长， 还是自我的任性 ？
              + 借鉴派
                  + 标准的活动组织
                  + 标准的评价办法
                  + 标准的活动品牌
                  + 标准的 …… 
              + 任性派      
                  + 开智特色
                     + 多培训团结合
                        + 写作
                        + 产品
                        + 编程
                        + 大牛资源  
                  + 5 元特色
                     + 5 元教 
                   

跟进上述的问题， 还是只是保留在直面上面， 到行为上面无非就是这么几件事情；

- 带头人 5WIH 
  - 组织者
     + 前期 CO 组织
     + 欢迎自高奋勇 
  - 支持者
     + 杂事处理
  - 参与者 
     + 要有输出和记录， 不是吃吃喝喝 
- 矩阵面基会
  - 月度
     + 写作 OR 编程
     + 老师分享会 
  - 周?双周  
     + CO 自己跟进自有资源考量 
  - 临时
     + 临时起意， 谁都可以 
  - 主题
     + 待定
  - 兴趣
     + 运动艺术都可以的召集  
- 输出接口
     + github
        + wiki + issue
        + gitbook or jianshu 

### 目标

第一期目标  201604 前

- 形成以深圳 CO 带头的固定面基会
  - 轮流组织
     - [ ] 8月第三周-写作班面基
     - [ ] 9月写作班面基
  - 可复用成果
     - [ ] 组织经验增补
           + 如何聚集人？
           + 如何让来众获得价值？
           + 如何选地？
           + 如何呈现？
           + 如何普及
           + 如何协作？
           + 标准是啥？
           + 判定是啥？
  - 派生输出成果 
     - [ ] 4 个 co 的项目召集
     
- 深圳可输出结果的召集， CO 带头召集
  - 虚拟小组
      + 团队协作
      + 迭代
      + 周报
      + 虚拟站立会议 
  - 创造过程
      + 创造记录
      + 折腾记录
      + 分享记录
      + 教程 or 手册 

上面两头实际上都是「聚人」。

人气起来， 人用起来， 人学起来， 才折腾出东西来。 那么， 这事就来了。

谁是负责人， CO 。
谁是牵头人， CO .
谁是收益人， CO .

so . 行动促成长。

#### 自我跟踪和靠谱工具

- 跟踪： GITHUB + ISSUE
- 靠谱： 5W1H

### 小结

- 输出到底是什么
  - 珠三角的组织， 是组织能力的输出
  - 互联网的项目， 可能是产品， 设计， 编程输出
  - 可复用的结果， 是标准和流程的输出
  - 吹牛的能力， 是当时直觉内化的输出

那么， 这些输出从何而来？

发自过去的经验， 发自过去的经历， 发自过去的种种。
种种， 都可以视为一种体验。

so . 珠三角的未来

- 三地的固定沙龙
- 固定项目的传道
- 可复用的经验组织传承
- 协同人员的增加
- 影响力的提升， 其实做好上面就哦了。

**Comment by ZoomQuiet** [comment]
在 2015年7月29日 下午11:39，gonghejian <notifications@github.com>写道：
> 珠三角 co-inn 名单接梗
>
> 14 小时内先尽力完成第一版接梗。 20150729 11:37 下午
>
> 背景
>
> 珠三角大区 co-inn 只有四位， 其中 75% 来自开智。 其中 3 位来自于深圳, 1 位福州。
>

嗯哼,提醒一句:

- 问题的提出背景不是这样触发的哪 ;-)
