### ISSUE TITLE
珠三角 8 月面基来了， 赶脚报名！ 截周日。

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/PRD#13]
> 本次活动在举办前 42 小时收到不少于 4 份临时请假， 人数少于 4 人。 三个汉子， 决定本周直接 FB 去。

> 最新的故事是 —— 又有一个汉子陷入无尽的忙碌。 8 月的面基只剩下两个汉子了。 依然举行 ……

按照珠三角的特色， 42 小时内上活动纪要 

## 珠三角 8 月面基

**重要**

---

### 背景

- 马上就结业了
- 马上就完课了

> 课程肿么多， 都理解了不？ 不理解也要写『大作业』啊。 还要输出啊。

### 活动信息

![](http://i1.s1.dpfile.com/pc/mc/796fe37e66cfe3e5113ee5ad703bd489(450c280)/aD0yODAmaz0vcGMvbWMvNzk2ZmUzN2U2NmNmZTNlNTExM2VlNWFkNzAzYmQ0ODkmbG9nbz0wJm09YyZ3PTQ1MA.7dbaa5a1b4e1025849018b4a409f9d4d/thumb.jpg)

- 时间： 周日下午 14:30
- 地点： [华侨城](http://t.dianping.com/deal/8199297) 
- 活动时间： 预计 2 小时

> 地址：华侨城恩平街创意园东部工业区E6栋103(康佳集团)   
电话：0755-86562916   
营业时间：周一到周四：10:30-23:30 周五~周日：10:00-01:00

### 如何报名

本周日晚上 16 日 晚上 20：42 分截止

> 不是写作班的可以参加不？
> > 可以的。 如果对珠三角， 没有见过面， 感兴趣的， 想了解写作班和编程班的都可以来参加。

![](http://img-storage.qiniudn.com/15-8-20/62614463.jpg)

罗宝线， 侨城东站 A 出口出来， 剩下的， 打开百度地图， 为您导航

#### 写作班成员

- 讲讲写作班学习到的分享， 最好能提前有文字输出
- 最后大作业的想法， 最好能有提前的输出构思
- 针对写作班当中需要解惑的难点收集

#### 非写作班成员

- 分享自己的故事， 参与讨论

### 活动流程

- 20 min 分钟自我介绍
- 1 hours 主题讨论环节一， 写作班分享和大作业
- 22 min 乱入， 我的故事要分享
- 20 min 自由讨论
- 聚餐， 看大家意愿

**Comment by Cloudtree11** [comment]
# **开智珠三角2015年8月面基 活动纪要**
## **时间**
20150826 11:40-13:00 1h20min
## **地点**
深圳市南山区高新南十路创维半导体大厦萃食广场3楼印象南洋
## **参与者**
Cloudtree、弓和箭
## **记录者**
Cloudtree
## **讨论内容**
### **开智社群与个人成长**
Cloudtree：**开智中的三类人**
> 
先自我检讨一下，近期自己在开智不是很活跃，没有很热烈地参与各种话题讨论和群内活动。由此我想引出一个话题，如何更好地借助开智社群帮助个人成长。讨论个人成长自然会对应不同阶段，我将开智的成员按阶段划分为三类人：
> 
>1. 未定型的在读学生（本科、硕博甚至高中）
>2. 刚出来工作的职场新人
>3. 工作3-5年及以上的职场老手
>
>我属于第二类职场新人。我认为，开智社群对于第一类和第三类同学的帮助是最显著的。第一类同学，相对有充裕的时间可以投入各项活动，更重要的是自己的职业和人生选择等会被开智影响和改变。第三类同学，在本领域已经有了一定的基础（经济、能力等方面），基本站稳脚跟，同样能够更为游刃有余地参与到开智中。
> 
>而第二类同学职场菜鸟，处在一个关键又尴尬的阶段。按阳老说法，职业生涯前两年是一个关键时期，新人必须在这段时间足够努力，超出身边人两个标准差以上。这就导致我们必须在此阶段专注在事业上，相比另外两类同学就没办法有更多的经理投入到开智社群的活动当中，特别是当你从事的领域与开智社群的交集不大（比如传统制造业）时。

弓和箭：**只是贴标签** 
> 
>这个想法有点问题。你按某个单一的时间维度划分出了三类人，赋予每一类人某些特征，再将自己对号入座。因为这类人怎么怎么样（设想），你也会怎么怎么样。这在我看来，是一个 **贴标签** 的行为。你过于强调自己的新人身份，其实完全没必要，没有人care，我们关注的是你能拿出什么东西（不要以身份做借口）。贴标签 是**Fixed Mindset**的表现，是一种过于简单粗暴的分类，据此指导自身的行动，更是谬误。每个人都是一个具体的人，能够聚到开智，是因为大家有着某种相近的气质。
>
>再者，用年纪或工作年限这个维度来区分人也不靠谱。许多工作多年的人经验和能力反而在下降严重，我也看到一些本科生甚至是高中生（比如开智社群中的某些同学）展现了一般是工作三五年的人才能具备的惊人能力。这说明什么？
>
>另外，即使是贴标签，也要意识到，标签也是有多个维度的，可以从多个视角切入，要学会**切换视角**，不要局限于单一的眼光。同理，**个人发展也可以是多线程**的，不是说你同时只能做一件事，适度并行才是进取的常态。你把自己当作一个容器，要思考如何整合和配置来自各方各面包括开智在内的资源和信息，助益个人成长，这是执行的问题。并且开智社群的成员也是多元的，各种各样的人都有，差别很大的人都能从中提取自己的养分。你所说的并不是问题。

Cloudtree：**那按积累程度划分？**
> 确实这个划分的看法不好，我修正一下。将所谓的成长阶段改为**积累程度**。很多人可能年龄很小，但起步也早，在某些领域已经有了庞大的积累量。我认为自己可能比开智社群很多的青年才俊晚熟一些，现在才刚起步不留，在初始阶段更应该静下心来做一些沉淀和积累。

弓和箭：**目标实例化**
> **建议确立目标时，少用「积累」、「沉淀」等模糊的词语。**我更倾向于定一个具体可量化有检测标准的目标，再一步步细分和拆解，最后落实到每一周或每几天需要完成的任务。这时，你处理的问题是，本周你需要完成什么，你怎么去做，Deadline是什么时候，成果如何交付，如何提炼总结，总结的模式是否可复用等等。不要在立一个模糊的目标，用一些大而抽象的词语概括，这样的想法永远只能困在你的脑子里，无法变成行动。该考虑的是这些。

弓和箭：**转换思路**
> 如何更好地借助开智社群助益个人成长的问题，不如转换思路，思考自己如何更好地参与到开智社群中。参与社群中一个或大或小的自己感兴趣的活动，在其中积极地互动和产出，在这过程中持续地用记录交付每一个时间段的成果，写下能够传承分享的经验，写出可复用的指导性方法路径。用自己的作品和成果逐步获得社群的认可，由边缘慢慢往核心靠近，慢慢做下去个人自然会有成长。你所公开记录和写作的一切，都是你个人品牌的奠基。要先**管理自己，再影响他人；先做好自己，再辐射他人**。这才是个人在社群中的成长之道。

### **珠三角大区群的发展**
Cloudtree：
> 区长对珠三角大区接下来的发展有没有设么规划？有没有想过如何调动更多人参与进来，我还是希望线上线下活动能够热闹些。（言下之意是目前大区线上线下活动的参与度不够。）

弓和箭：
> 
首先，开智设置北上广三个大区的意义，是为了开智社群下一步的发展和扩张铺路，设立据点，发展好当地的群众基础，积累和吸引各地优秀资源。

> 其次，你要承认一个现实：每个人都有许多个圈子，开智只是其中之一，单纯由网络维系的联系其实是很弱的。你期望看到许多人积极参与，热热闹闹的场面，并不现实。

> 不过，定期的面基作为一种线下互动方式，自有其意义。即使每次只有三五人参加，能集中讨论一两个话题，结束后及时反馈产出跟进，也可以作为一种额外的敏捷轻盈个人成长短路径。有效果，但局限放在这里，你不能对此期望过多。

Cloudtree：
> 嗯，那还是我太理想化了。

### **写作的意义和提问的诚意**
弓和箭：
> 讲两点编程班反复强调的理念。
>
- **写作作为自我管理的工具**
> 不管学什么东西，做什么工作，任何一个持续投入的过程，都可以用写作来记录和跟进事项，反馈状态，给自己施加压力立Flag，逼迫自己行动。每次写多写少无所谓，及时写，持续地写，做了要写，完成不了任务也要写。以面向新人、指引新手的姿态写作，教是更好的学，能从自身经验中抽取出可复用的模式，那就是更高的标准了。
> 当你在某一项事务或某一个领域有了十万字的积累后，不能说接近专家，但至少已经具备了能够被人认可的专业水准，超出平均值至少一个标准差。也就是说肚子已经有货，足以高质量地侃侃而谈了。
> - **提问的诚意**
接上一点，今天的讨论你提了好几个问题，所以说说提问。好的提问应该是在你付出了一个阶段的行动，输出了一定成果的基础上抛出问题。比方说你提一个问题时，先说明你做了什么，把行动过程的笔记Po出来，内容越充分越有意义，这才是有诚意的提问方式。所以，当你下次要提问时，不妨先反思一下，我这个提问的诚意在哪里？有多少？份量够不够？

Cloudtree：
> 感受到不小的压力。

弓和箭：
> 你在谈话的内容中感受到压力山大，或许是因为你积累不够，做过的东西太少，能拿出来的东西太少。当积累了足够的作品后，你才能由我的话题，带出自己的内容。

**Comment by Cloudtree11** [comment]
直接用对话体了……凭记忆重构对话内容，如有曲解等失误，区长再补充指正。

似乎还缺一个个人总结？！……后面填坑，先想想。

**Comment by ishanshan** [comment]
>如何更好地借助开智社群助益个人成长的问题，不如转换思路，思考自己如何更好地参与到开智社群中。参与社群中一个或大或小的自己感兴趣的活动，在其中积极地互动和产出，在这过程中持续地用记录交付每一个时间段的成果，写下能够传承分享的经验，写出可复用的指导性方法路径。用自己的作品和成果逐步获得社群的认可，由边缘慢慢往核心靠近，慢慢做下去个人自然会有成长。你所公开记录和写作的一切，都是你个人品牌的奠基。要先管理自己，再影响他人；先做好自己，再辐射他人。这才是个人在社群中的成长之道。

刚好前两天在和群友的聊天中也讨论过这个问题，为什么都知道开智社群有很多让自己成长的资源，每日翻聊天记录但其实自己却觉得并没有太多收获？我想这可能是因为，自己把开智新青年微信群当成了「单向的」「碎片的」输入入口，而不是输出的出口。

微信群作为沟通工具中的一种，开智社群作为我们所在社群中的一个，想要靠开智青年微信群中单向且碎片的输入获得成长，这个真的不现实。更合适的做法，如 @弓和箭所说，是在按照自己节奏探索的过程中，持续记录交付每一个时间段的成果，写下能够传承分享的经验，写出可复用的指导性方法路径。

输出自己的作品/成果、交流收获，获得反馈，让下一步的探索找到更清晰的方向，这才是个人能在学习型社群中飞速成长的打开方式。

**Comment by lywpro008** [comment]
写作的意义和提问的诚意

弓和箭：

讲两点编程班反复强调的理念。

写作作为自我管理的工具 不管学什么东西，做什么工作，任何一个持续投入的过程，都可以用写作来记录和跟进事项，反馈状态，给自己施加压力立Flag，逼迫自己行动。每次写多写少无所谓，及时写，持续地写，做了要写，完成不了任务也要写。以面向新人、指引新手的姿态写作，教是更好的学，能从自身经验中抽取出可复用的模式，那就是更高的标准了。 当你在某一项事务或某一个领域有了十万字的积累后，不能说接近专家，但至少已经具备了能够被人认可的专业水准，超出平均值至少一个标准差。也就是说肚子已经有货，足以高质量地侃侃而谈了。
提问的诚意 接上一点，今天的讨论你提了好几个问题，所以说说提问。好的提问应该是在你付出了一个阶段的行动，输出了一定成果的基础上抛出问题。比方说你提一个问题时，先说明你做了什么，把行动过程的笔记Po出来，内容越充分越有意义，这才是有诚意的提问方式。所以，当你下次要提问时，不妨先反思一下，我这个提问的诚意在哪里？有多少？份量够不够？


这两个部分刚好也是我最近在思考的元问题，开智的优势是在于大家一起探索学习和提问等元问题，因为有记录，有比较，所以验错性很强。对于请教，我本人也是倾向于po出行动过程的比较，除了诚意以外，还容易提升提问效率，新手和老鸟对于同样的问题，条件反射的路径肯定不同，这么说吧，相对于问题的答案，找答案过程的优化意义更大。

**Comment by badboy315** [comment]
赶脚终于有些 「梗」 的感觉了

**Comment by ImCaos** [comment]
怒点42个赞，珠三角如此高质量的面基让人受益良多啊
