### ISSUE TITLE
「开智同侪汇」水牌分享及众包号召

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/PRD#15]
![幻灯片4.jpg](http://upload-images.jianshu.io/upload_images/32598-1c22ce48d42c1b09.jpg?imageMogr2/auto-orient/strip|imageView2/2/w/1240)

鉴于开智面基缺少一面旗帜，俺先本着最小产品原则，做出了一个水牌demo。

嗯，技术有限，采用PPT制作，以下是PPT源文件以及pdf下载地址

链接: http://pan.baidu.com/s/1ntEILfV 密码: iqnt

欢迎忍不住此设计的同侪可我索取ai文件，做出更符合开智气质的东东。

**Comment by ZoomQuiet** [comment]
首先得将 .ai 分享在列表中哪,,,
