### ISSUE TITLE
统一助教团开课前讨论

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/PRD#16]
- 录音: 
   + http://openmindclub.qiniudn.com/res/tapes/omooc/150907_2.py_0_why.MP3
   + http://openmindclub.qiniudn.com/res/tapes/omooc/150907_2.py_1_qa.MP3
- 梗提醒:
    + 到底如何解决全国的实时语言交流问题?!
    + 助教的面基主持研究要准备些什么?!
- 参考: [珠海[f2f] 记要 · Issue #7 · OpenMindClub/PRD](https://github.com/OpenMindClub/PRD/issues/7)

**Comment by csufuyi** [comment]
补充大妈提的助教主持剧本：
如何控制气氛
如何组织注意力
如何经营兴趣点
如何营造成就感
根据什么来引导形成臭味相投的小团伙？
