### ISSUE TITLE
OMPRD广州[C2T2]+7

### ISSUE THREAD

**Issue by tonyyet** [OpenMindClub/PRD#17]
### 时间

2015年9月17号（星期四）晚上7:00-9:00

### 地点

猎豹公司 3110 会议室 ;-)

### 参加者

请大家在此贴子底下留言，报名参加，并且简要说明自己要分享什么内容，或者带着什么问题来现场希望获得解答

报名截止时间：本周四（9月17号）中午12点42分

如报名人数少于5人，本次活动将自行流散。

### 议程

1. 自我介绍
2. 闪电演讲
3. 现场代码 / 现场写作 / 现场翻译 / 现场谱曲 / ...
4. 自由讨论

#### 五分钟闪电分享（Five minutes of fame）

形式：自由演示 / 演讲，可以用幻灯片，也可以不用
时间：五分钟以内
目标：展示自己在做的项目，征集智友参与自己的项目，分享自己在学习的东西……

范例：

- 张三：我的下一个卫星计划（嗯，这是[完全有可能的](http://www.cubesatkit.com/)。。。）
- 李四：我的下一个纪录片计划

---

以上基于大妈的[C2TC](https://github.com/OpenMindClub/PRD/issues/10)进行修改。

**Comment by tonyyet** [comment]
报名：Tony Yet 

分享内容：旧金山见闻分享（noisebridge, 826 Valencia, exploratorium）

**Comment by ZoomQuiet** [comment]
- 报名 大妈
- 分享:
    + 现场编程,多公众号响应后台
    + 苦短衫的故事 ~ 如何勾搭大牛?!

**Comment by benafrant** [comment]
报名：刘果林
分享： 寻旧书的好时光

**Comment by badboy315** [comment]
如报名人数少于5人，本次活动将自行流散。

~~~ 才 3个人 哪 ~~~~~ 加组织者

**Comment by ZoomQuiet** [comment]
但是,正常 fb 哪,,,
提前到 19:00 来猎豹 门口集合 ;-)

On Thu, Sep 17, 2015 at 3:06 PM, gonghejian <notifications@github.com>
wrote:

> 如报名人数少于5人，本次活动将自行流散。
>
> ~~~ 才 3个人 哪 ~~~~~ 加组织者
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/PRD/issues/17#issuecomment-140988381>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
