### ISSUE TITLE
珠三角 9 月同侪汇召唤纪要

### ISSUE THREAD

**Issue by Cloudtree11** [OpenMindClub/PRD#19]
> 
> 珠三角9月深圳同侪汇如期而至~~~
>

# **开智珠三角 9 月同侪汇**
-----
## **背景**

- 天气热度不减的八月和九月，开智社群线上线下的活动继续精彩纷呈：一期写作课刚落下帷幕，二期 Python 班又风风火火地开始预热，全新召集的「社群合伙人」为我们带来了「开智一刻」等创新的活动……与此同时，开智不同领域的许多小伙伴们，这一个多月想必又有了自己进一步的思索、积累和收获，会有许多值得和大家分享的干货，各种想法也需要相互碰撞。线上的交流难免有限，让我们在线下继续，珠三角九月同侪汇再次到来！

## **活动信息**

- 时间： 2015 年 9 月 27 日（周日） 14：00 - 16：00
- 活动时长： 2 小时
- 地点： [深圳华侨城如盒艺术空间](http://t.dianping.com/deal/8199297)

![Alt Text](http://i1.s1.dpfile.com/pc/mc/796fe37e66cfe3e5113ee5ad703bd489(450c280)/aD0yODAmaz0vcGMvbWMvNzk2ZmUzN2U2NmNmZTNlNTExM2VlNWFkNzAzYmQ0ODkmbG9nbz0wJm09YyZ3PTQ1MA.7dbaa5a1b4e1025849018b4a409f9d4d/thumb.jpg)

> 地址：深圳华侨城恩平街创意园东部工业区 E6 栋 103 (康佳集团)
>电话：0755-86562916
>营业时间：周一到周四：10:30-23:30 周五~周日：10:00-01:00

- 交通路线：地铁**罗宝线 - 侨城东站 - A 出口**，使用手机导航路线步行到达

![Alt Text](http://i3.tietuku.com/8b46ba7840a5b3b2.jpg)

## 如何报名

- 开智 PRD 珠三角大区微信群回复
- GitHub issue 回复
- 邮件列表回复

> 如果报名回复里能加上可以和大家分享的主题就更好了。

- 截止时间：2015 年 9 月 26 日（周六） 20：42

## 活动流程
- 20 mins 分钟自我介绍
- 30 mins 主题讨论环节一：待定（如编程与Python班等） 
- 30 mins 主题讨论环节二：待定（如开智活动策划等）
- 20 mins 群友个人故事分享
- 20 mins 自由讨论
- 集体合影留念

## 活动反馈

珠三角老规矩，参与者需要在活动结束后**42小时**内在issue中提交活动纪要或个人总结。

**Comment by badboy315** [comment]
报名 ……

**Comment by wong-github** [comment]
报名

**Comment by Cloudtree11** [comment]
# **@黄雷基 老师的活动纪要**

> @黄雷基 老师对自己所分享话题的纪要。

## **从一种配乐趋势说起**

### **3段音乐**

1. [Philip Glass - The Hours - 02 - Morning Passages](http://music.163.com/#/song?id=1828633)
2. [私人农场bgm](http://site.douban.com/luobugen/)
3. 壮族欧贵场景配乐（未发表）

### **分享内容**
1. 我们站在配乐行业的角度寻找**时间源头**。配乐行业的时间源头可以认为是好莱坞，也就是影视工业最发达的地方。
首先因为传统调性音乐技术由于存在较大共性，只要你懂得听的技巧和具体的音乐的知识，你可以轻易跨越国界去获得一些比较先进的观念。
我们观察到，在发达国家，音乐在学界与实用领域之间的界限越来越模糊，学界创造的诸多音响，被更广泛地使用，而时间源头的好莱坞同时也创造了大量的创意不断地去反馈给学界，并迫使学界与其产生更密切的合作。
2. 国内的音乐学院基本上还是一个**象牙塔**，创作实践基本与大众脱节，也并不关心技术下放到商业实践的问题。现在配乐行业特别是游戏配乐从业人员大多不是专业作曲科班出身，近两年这个情况才有所改善，然而依然只能是靠学院派中的个体兴趣为导向，才得到部分解决。
3. 我们看到未来音乐依然是多种风格并存，不过可以把握到一些趋势：

> 
- **电子音乐**，更准确地说是简单明快的电子舞曲或将成为一种最主流的趋势
- 配乐中**简约主义音乐**技巧的使用也逐渐成为一种业界的时尚做法
- 音响设计上音乐的**无压力听感**也将成为一种大原则。

**Comment by wong-github** [comment]
记录人：贤斌（黄贤斌）

时间：2015年9月27日 14：00 - 16：00

地点：深圳华侨城如盒艺术空间

参与者：共6人，弓和箭，Kelly　－　巧玉，cloudtree，高秋琪，黄雷基，贤斌

## 个人分享
- 弓和箭
 1. 用 Github 提高自我协作度。由于 Github 的私有库需要收费，因此可以用 Bitbucket 来记录私有的东西，并协助自己办公
 2. 如何更好地使用 Github 的功能。 Github 功能简介，三层关系：库是最终的成品，wiki 是制作过程的手册，issue 用于讨论，issue 中的事情讨论完毕后可以转移到 wiki 。Github学习教程可参见 http://git.oschina.net/progit/
- 高秋琪
 
	目前在开智正典创作中，阅读夏丏尊的著作时发现从文言文到白话文之间的过渡衔接不好，接下来想着手了解书面语从文言文转到白话文的过程中，是谁在重建中文的书写规范这一问题。
- 黄雷基
 
	目前音乐领域中学院派与商业的接轨愈发密切。学院派追求自我本能和直觉创作，理论体系严谨但受众少。学院派中的异类：所创作的东西具有学院派的影子，但其技术具备可复制性，如简约派。这种风潮与电音的发展，一并丰富了音乐创作的多元化。未来音乐人的“音乐匠心”将是核心创作要素，缺少音乐素养将不能理解其中的音乐语言。
- 贤斌（补充）

	前阵子看完《硅谷之火》，这是一部叙述PC发展史的书，书中除了讲述微软、苹果、甲骨文等巨头跌宕起伏的发展史及其创始人的经历外，也花很大部分笔墨讲述了Edward Roberts、MITS、帕洛阿尔托研究中心、霍姆布鲁计算机俱乐部等人们较少提及的创业者、小公司、机构等在推动PC发展中所起到的巨大作用。

	透过PC的发展史，再对比目前火热的互联网，我觉得两者还是有不少相似之处的，比如：其一，两者都是基于半导体技术的进步才得以发展的，PC时代得益于CPU性能的提升以及半导体工艺的进步，而互联网时代（基于移动端）则得益于SOC不断提到的集成度以及半导体工艺的进步；其二，前期过后都是以软件的发展为主，同时网络也成为重要的发展动力。当然，两者也有很多相异的地方，最明显的一点，我们可以感觉到，在PC端技术发展的积累下，互联网时代的技术发展和迭代速度要比PC时代快得多，同时其开源性更强。

	历史如镜，一名技术人员如果能了解某个技术领域的发展史，我觉得能在一定程度上能让他/她看待、思考问题的角度多样化，有助于其对技术发展趋势的研判。

## 交流精句

进入开智，让自己发现人生有更多的多样性。

困难，扛不住就成了压力，扛起来就成了动力。无论写作班还是编程班，独自一人学习，很难将知识内化，所以线下交流很重要；开智课程的学习是远程学习，与传统教学相比有很多地方不可控（如学习时间、学习资料等），因而更需要保证时间投入，所以线下交流能让学员即使在进度暂时脱节的情况下也能重新聚焦回课程，跟上进度。

同侪会的意义：群友见见，促进感情；线下交流，提升效果更好（如python班）；核心在于同侪压力，push 自己坚持下去（80% - 90% 的人在没有外部压力不足的情况下会放弃目标）。
## 个人感受
第一次参加开智的线下交流活动，看到区长、黄老师、高秋琪能轻松自如地分享大段干货时，我确实感受到了区长所讲的同侪压力。究其原因，还是自己的积累太少，真的需要多读书，多记录，多输出，同时也需要了解和学习牛人们的思维方式。

**Comment by Cloudtree11** [comment]
# **开智PRD同侪会 深圳 20150927 活动纪要**

## **记录人**
Cloudtree
## **全程录音**

> 链接：http://pan.baidu.com/s/1qWqYJxU
密码：30zk

- 自我介绍 00:14:40 开始
- @弓和箭 分享 00:52:00 开始（**01:00:30 - 01:01:15 手机铃响，噪声很大，请绕过**）
- @高秋琪 分享 01:20:15 开始
- @黄雷基 分享 01:37:00 开始

本期 PRD 同侪会内容精彩，气氛活跃，推荐大家听录音感受一下 :）。

## **弓和箭的分享**

### **示范如何使用 GitHub 进行协作**

- 演示视频

> 链接: http://pan.baidu.com/s/1kTCN9p9
密码: g72n

- 内容
    + 公开库使用GitHub，免费个人私有库可以使用[Bitbucket](https://bitbucket.org/)
    + 基本使用
        + 命令行和快捷键
            + 如何记住快捷键？ 
             使用快捷键壁纸，使用时直接切换到桌面查看。
            + 提交修改和更新的git command
                + `git add .`
                + `git commit -m "test"`
                + `git push -u orgin master`
                + `git pull`
        + 对比提交记录
            + `Edit` -> `Page History` -> 选中对比的版本 -> `Compare Revisions`
+ 协作方法
    + Wiki、Issue、Readme
        + Repository 仓库
            + 存放源代码
            + Readme 面向刚加入新人的指导说明
        + Wiki 讨论的最终的成果（终版，交付的内容）
        + Issue 发起话题，讨论跟进，持续追踪。
            + 自动邮件提醒
+ 为什么要使用GitHub？
GitHub最开始是程序员写代码在用，但后来越来越多人发现，这套模式和方法不只限于程序员，完全适用于更一般的**创作者**（比如作家、音乐创作人等），它能提供给创作者一套完整的创作和协作生态。
+ 相关推荐资源
    - [官方文档](https://help.github.com/index.html)
    - [Pro Git](http://git.oschina.net/progit/)
    - [廖雪峰的 Git 教程](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)
    - [GitHub秘籍](https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.zh-cn.md)

## **高秋琪的分享**

### **现代中文的流变**

- 撰写《开智正典》中介绍《文章讲话》的文章，开始研究夏丏尊先生的治学及人生经历，将书与人放到更大的中文变革环境下，连接过去与未来。
- 文言文到白话文的流变
    - 从大陆翻译的外国作品大多难以阅读谈起，大陆现代中文受英文和政治等的影响，抽象名词滥用（《论的的不休》），啰嗦无美感。
    - 夏丏尊先生的《文章讲话》，将句子和文章作为最小单位，分析最小结构，类似于E.B.怀特的《风格要素》，给出简明的写作原则，这些原则也符合后来认知科学的研究。
    - 谈白话文不能不谈「新文化运动」，胡适和钱玄同等人提出了对于新中文的激进主张，而夏丏尊先生选择了另一条路径。而现在看来，夏先生所做的学问仍能对当代的语文教学中有帮助和启发。
- 欧美语言学框架
    - 学习西方研究语言演化学者的研究成果（如平克的《语言本能》和《心智探奇》等作品），了解关于人类语言习得过程的研究。从演化论和认知科学的角度思考语言。
- 希望借鉴古今中外前人多个方向上的探索成果，找出重建中文书写规范的思路，一步步往前，找出白话文该有的真与美的样子。

### **延伸讨论**
- 区长提问：
是否有试着去阅读古文，如《资治通鉴》等？
- 秋琪回答：
    + 古典文学方面，古诗词接触得比较多，如辛弃疾等。文章方面读过《古文观止》，读过几十篇韩愈的文章，但确实没有像中文系的同学系统地进行大量的古文阅读。
    + 阅读文言文遇到的困难时读得太慢，阅读速度上不来，效率很低。
    + 中文方面，读的比较多的是**余光中、王鼎钧、夏丏尊、林沛理、王文兴**几位的作品，对古代中文的了解，目前这几位作者的评论之上。同时现在也在阅读西方文学原著，以此了解外国文学和练习英文。
- Cloudtree注：探寻好中文的样子，古代文学（包括诗歌和文章）这个瑰宝是不能错过的。对于以上提到的阅读文言文的困难，其他开智群友们是否有好的建议？

## **黄雷基老师的分享**

### **播放三段音乐并由此分享**

- 时间源头观念：配乐的时间源头是好莱坞，影视工业最发达的地方。
- 音乐产业，学界和实用（商业）两个领域原本处于分立甚至有些对立的状态（学界鄙视商业领域）。但近年来有些学院出身的音乐人也会进入到商业领域，给配乐业界带来了新的风格和趋势。这种音乐非常有技术含量（学院派的功底），但又很容易让普通听者接受，听起来很舒服。
- 流行风格简单明快的电子音乐会是未来音乐发展的主流趋势，这方面与技术发展密切相关，音乐创作人也在不断摸索之中。

**Comment by Cloudtree11** [comment]
呃，坑还没填完……

Cloudtree 的个人总结在北京时间 20150930 06:00 前交付。

**Comment by ZoomQuiet** [comment]
so nice!

hope keeping
make out the om world in PRD

On Tue, Sep 29, 2015 at 2:59 AM, Cloudtree <notifications@github.com> wrote:

> 呃，坑还没填完……
>
> Cloudtree 的个人总结在北京时间 20150930 06:00 前交付。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/PRD/issues/19#issuecomment-143844212>.
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by Cloudtree11** [comment]
# **开智 PRD 同侪会 深圳 20150927 个人总结**

## **总结者**
@Cloudtree
## **总结内容**
### **触动：分享内容的差距在于背后的积累**

9月开智 PRD 同侪会深圳聚会，@弓和箭 、@高秋琪 和 @黄雷基 老师三位都做了精彩的主题分享，具体内容大家可以查看活动纪要，在此不准备展开评论。说说这个过程中对我触动比较大的一点：我观察到，分享过程中，几位在短短的十几二十分钟内以极快的语速输出了丰富密集的内容，整个过程的信息密度很大。会后我和 @贤斌  讨论时不得不承认，在现场听时，我们发现自己一时消化不了那么大的信息量，头脑一时处理不过来。要在会后听几遍录音复习，才能真正理解分享的话题、其内在逻辑结构和精妙之处等。之所以体会到这点，是因为我和 @贤斌 本来也准备了自己的分享话题（虽然最后由于时间关系没有分享），我的分享话题是『Debug也像破案——是程序员也是侦探』，@贤斌 分享的内容是《硅谷之火》一书的观点。二者对比，我们原本准备的话题内容太少，信息结果也过于简单。

差距在哪里？其实是背后的积累程度不同，在所分享领域的积攒的工夫不在一个数量级。三位分享者看似轻巧实则功力尽见的分享，是建立在对该领域足够深厚的积累之上的（积累意味着实践参与、文献阅读、笔记输出等形式的多种组合）。再次提下 8 月同侪汇讨论到的一个点，即当你在任何一个领域的输出文档积累达到 10 万字以后，就代表着跨入一个新的境界，足以信手拈来地做出一个信息密度足够大，质量内涵又充足的分享和评论。这时候，所谓口才好不好什么的已经不重要，因为你肚子里已经存了足够的干货，随便倒腾点丢出去都足以让人惊叹（这方面阳老是典型代表）。

这也是开智社群同侪压力的一种，没有亲临现场感受，是无法感受到这种冲击的，被 Push 到的感觉很强烈。大家可以通过录音感受一下。

这是我们所感受到的差距。好，看到差距了，那下一步的行动？如何执行和跟进？这是另一个值得思考的问题，下面内容会稍微提到。

### **对开智 PRD 8 月深圳同侪会讨论内容的个人反馈**
8 月同侪会和区长对谈，写了份[活动纪要](https://github.com/OpenMindClub/PRD/issues/13)，有不少群内的小伙伴看到了。在此后，分同学可能会感兴趣，后面我有何改变，行动了吗，如何行动。9 月同侪会上，区长也直接向我发问：『一个月过去了，你停留在想的阶段吗？』

仿佛开启了某个潘多拉魔盒，开智社群的压力直接向我袭来，就算无人提起，我也必须给大家一个回复。

总结一下，上次对谈，暴露出自身的问题是心智僵固，囿于观念，行动不前。原因是一方面，重要的是如何开始行动并记录跟进。老实说，自身的转变还不够大，但还是愿意 Po 出来让大家跟进：

- 思考方式上。开始试着不去纠缠得失权衡资源配置等问题，转换思路，围绕最小意念构筑最小行动，即由一个足够渴望的想法出发，直接落地，思考如何行动并执行。（思路上的转变，暂无可跟进交付的成果。）
- 开始记录每天的生活事项，主要是工作和个人管理事务，分析以前的记录校正当前的规划。目的是定期检视个人精力投入情况和成长进度。（这部分放在私人笔记软件中，暂时未能公开。）
- 工作上，此前对自己从事的技术方向迟疑有困惑。反问自己后，认为自己还是喜欢这个方向的，于是不再犹豫，开始在这方面的研究和技术积累。（目前还在整理内容，后续迁移到 GitHub 仓库上，作为可交付文件持续跟进。）
- 报名开智二期 Python 班，认认真真地完成新手任务到 Task:3 （只提交了4天的记录，还是不够尽力）。捡起了之前放下的 Learn Python the Hard Way 学习。

好，上面讲的都还是不够清晰具体量化，那么直接说， 10  月内需要交付的东西：

- 个人工作技术积累的 GitHub 仓库，其中有持续跟踪的内容。
- 按照 Python 班要求的学习记录日志，跟上课程进度不掉队。
- 输出 4 篇读书笔记（主要是开智正典的阅读书目），发表到个人博客上。

还有做得不好的地方，上次讨论到如何借助开智社群帮助个人成长，结论是要更加主动积极地参与群内活动，通过自身的作品和输出获得社群的反馈。这点没做好，这一个月没有以更加积极的姿态参与到开智青年群的活动中，时间线长期滞后，一直是『追聊天记录的人』。第一步需要先赶上时间线，第二步是整理聊天记录中已有的资源，这个思考还在继续。

**Comment by Cloudtree11** [comment]
呃嗯……感觉挖了好几个坑 ╥﹏╥...…

**Comment by GQiuQi** [comment]
iMac出了点小问题。写是早就写好了，今天才得已上传我的纪要，抱歉啊。


### Github的使用
对Github一直存有刻板印象，以为那里只是程序员的世界。对我这种，编程经验仅仅止于《奔办法学python》第26讲的小白无关。

可谁又说程序员不能改变世界呢？

使用私有库建立个人文档，将Github视为长期交流之场所，讨论内容定型后建立公开wiki。便会大大弥补微信群散点讨论，无法久留的问题。更可为个人的学习建立“进度条”。

**Github学习资料**

- 官方文档；
- 珠三角内部wiki；
- 廖雪峰博客上的Github使用指南；

**免费私有库**：http://www.bitbucket.org

### 科学上网
人在不在内地，没听 …

叨叨一句。看现在的情况，还是自己买个服务器吧。一年三百，私密一点。

### 高秋琪的个人简介

生于江苏，现居深圳，求学澳门。

参与Pinker *the sense of style*中译。

**分享内容**：
现在在研究夏丏尊先生和他的白话文教育理论，借此机会对白话文的流变做了一些粗浅梳理。

白话文的转变，非常复杂。欧风美雨，再加之文革对中文的污染，背后的复杂变量太多。感兴趣者，可从余光中先生的评论文章入门（《青青边愁》，《分水岭上》，《望乡的牧神》等书）。以及，林佩理的《玩转中文》。

其实，“的”“的”不休，抽象名词滥用只是结果。中文之式微，失败的语文教育，难辞其咎。

好，如你所知，这件事情你我无力改变。那么，至少先来看看大师是如何指导当时青年的。

首先，从句读入手，厘清现代标点进入后，中文的改变。进而确定文章不可分割的最小部分：语句。
再次，明确文字表述目的与情态。是动是静？心中意念是否与笔下文字统一？
以及，作文时，有限文字如何省略，如何言有尽而意无穷？

最末并非微末，中文写作，始终对大而话之的“道”青睐有加。可无有效体系，只能依靠经验 … 看到这，你是否想起了某个学科？嗯，中医是也。

而夏丏尊，作为教师，对写作认知完全源自于教学实践，写作时，心中读者也是学子，避免了书斋中大先生的自娛自樂。其用毕生实践不断修正的观点，也因此得以长久。

比如，他建议写作要着眼于传达具体感觉，与pinker口中的“心智之眼”何其相似。

最珍贵，莫过于他的西学背景与刻苦精神。提纲挈领，将写作的手法一一分类列出。比如，将文章的动态。就将其再次细分为“片段的动作”与“连续的动作”。甚至，他还计划，将四大名著中，同一形式的句子一一圈出，令学生可快速理解中文的形式。呜呼，可惜先生的早逝，这一计划并未实现。

另一件事，则是，给定义。面对“文气”这一传递千年，却只能依感觉评判的模糊概念。你，身为创作者的你，该如何面对？

夏丏尊居然给出了它明确的定义。

破天荒。

### 语言，之为本能

最近在以主题的形式阅读语言学著作。

正如pinker所言，人类的高贵理性，并非是仅存于爱因斯坦身上。而是属于那些，依靠大脑本能、母亲式语句的输入，而自然习得语言的四岁小童。

p.s：因为这一部分还在不断了解中。思绪有一些迷糊。就分享到了这里。

下面是想看看。依靠实证的语言学研究和夏丏尊著作中的深层思想有没有联系。
