### ISSUE TITLE
[f2fZH]7.9 @douzhipin  日本造星机制培训

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/PRD#21]
## 20160709 @douzhipin  日本造星机制培训

⌚️：20160709 16H30-18H

🏡：清华科技园A901

👨：@douzhipin，@aJiea，Cara 及思芙美妆社区运营组员

## 不是不要优秀的人

    “创造力只不过是把事物关联在一起而已。” —— Steven Jobs
    
学校优秀 vs 职场优秀
1. 学校学习的单向性。容易成为优秀学生。
2. 工作中，自己的优秀建立在团队协作上，想要变得优秀，不单是自个儿的事儿

最优秀的vs最合适的
1. 最优秀的人才不定是适合的
2. 最优秀的解决方案不定是最有效的

## 主题研究

翻开《智慧社会》，MIT 人类动力学实验室主任 Alex Pentland 在另一时空讲述大数据与社会物理学；打开电视，主播预告今晚欧洲杯决赛现场准备情况；接到妈妈打来电话，告诉我这个周末她有做了什么事……把A知道的事物告诉B，此谓沟通。

从鸡毛信到智能电话，从方法论到认知学科，自古以来人们做的事儿无外乎解决沟通问题和提高沟通效率。

解决沟通问题3要素：
- 如何把A知道的告诉B
- A是否知道A自身知道什么
- 如何将A知道的量化

主题研究是解决沟通问题的一种方式：受环境驱使（个人要求or环境要求），帮助研究者梳理知识间结构（已知未量化知识或未知待探索知识），研究过程认知方法可复用。

## 人间差距研究：想法流形成，收获想法的过程

    “你的成功在很大程度上取决于你探索的质量，并进而取决于你所拥有的信息及想法来源的多样化和独立性。”
    “人们的决定是个人信息和社会信息的混合体，而且当个人信息较弱的时候，人么更依赖社会信息。在人们不确定的情况下，社会学习对于提升自信心起着更大的作用。”  —— 《智慧社会》

SOCIAL LEARNING 
社会学习，即新想法如何成为习惯，以及如何通过社会压力加速影响学习。包括通过观察他人行为学习新策略以及通过体验或观察学习新信仰。

ECHO CHAMBER SITUATION回音室效应
人和人沟通，点对点之间存在大量空白区域。信息和想法在一个封闭的小圈子里得到加强。连接少，社会学习机会少，反馈循环网络中，只能反复听到相同的想法。

保留微信群，成为连接各个领域世界的的点，正是让社会学习领域更加多样化。

在相对封闭的环境，研究现有优秀人才做事过程，复制优秀人才。

---

改进点：
1. 主题研究可以多有
2. 关注收获想法的过程
3. 调用和平衡可控资源和非可控资源

**Comment by aJiea** [comment]
[【部分培训录音】]( http://zoomq.qiniucdn.com/ZHGDG/2016/160708-jp-fans/index.html)

**Comment by bambooom** [comment]
不是很资道为毛被大妈 assign 了~ 😅

前面的总结貌似很高深, 就不多嘴了.....
但是听完录音, 比较同意 @douzhipin 的说法, 希望偶像是可以长期的~

不仅是现实的偶像, 就连喜欢的美剧/动画/漫画都是一样啊~

最近热衷补 CSI:LV, 看的久了, 会觉得那个团队的感觉好棒, 随便走了某一个角色都会伤心好久😢, 需要一段时间才能接受新来的角色 (只是随意的吐个槽)

**Comment by ZoomQuiet** [comment]
DIE by over deathline! 逾期/失格/无用ed
