### ISSUE TITLE
160719 C2T2sz 纪要

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/PRD#22]
## Info

13:23~15:22 桃园 烧麦

- 列席: 大妈/老高/free/弓箭/达达/巧玉/钱子游/ivanlau
- 议题: 
	- 初创公司程序员成长
	- PyCon2016China深圳
	- OMKM
- 录音:
    + DAMA版本:[160719C2T2sz/](http://openmindclub.qiniucdn.com/res/tapes/omprd/160719C2T2sz)

## Task

所有现场列席群友:

- 48 小时以内在指定 Issue 上回复,提交自己的记要
- Free/弓箭 议题一 特别作业, 给出自己的方案

**Comment by ZoomQuiet** [comment]
## DAMA

- 预备的三议题:
    + KMOM 的期待
    + PyCon2016China 的可能掺合
    + Maker 在深圳的 OM 关联
- 但是, 现场气氛走向,立即进行了对应修订
- 弓和箭 给出了小型创业团队的成员成长评估方式问题, free 附议:
    + 现场交互梳理
    + 自身有问题困惑, 但是主动挖掘/研究不多
    + 有相关组织管理者经验的肯谈, 但是,不知道具体的问题列表无法探知思考/实践阶段
    + 只能逻辑推导,给出一个思考方向:
        * 无论新人/老人
        * 一个相对公平/公开的衡量指标
        * 个人成长速率
        * 又如何能结合到具体的制度上来进行推行呢?
    + 以及暗示了一个坑:
        * 评估的绩效,是否以及如何同薪酬挂勾?
- PyCon2016China 首次进入深圳
    + 老高是从珠海奋发北漂深圳的社区老人
    + 相互引荐时发现一个问题:
        * 开智社群竟然没有一个统一的,深入人心的自述
        * 现场所有社群成员,给出了三个版本的说明
        * 旁观成员, 又给出了另外一个方面的观感
        * 只有一位, 给出了一个现实基础版本
        * 建议, 开智社群在发展,连 logo 都在进化
        * 那么, 开智社群的自述, 应该以 140 字为界, 进行长期的迭代,传播,宣传!
- OMKM 筹备中的新型自助式课程, 但是缺少一个切入点
    + 所以, 引导大家回顾对比出 dama-style 的构成
    + 的确定义出了一个全新的元素:
        * 有固定的模式条理化处理任何命题
    + 并发现 KM 习惯的形成真正基础动机是~穷...
    + 这也是一个意外的发现...回顾小学开始的知识管理行为演进的原点时发现

**Comment by csufuyi** [comment]
一  

弓箭提出初创团队如何考评程序员的问题.
大妈给出的观点是:小团队不需要繁杂的KPI体系, 应主要考察

+ 其与自身对比的成长速度
+ 与他人的分享沟通的频次和质量

鹅厂对工程师到高级工程师是有一套评价体系的, 简单说来是三级:  
  
+ 放心. 团队分配的模块能按进度和质量完成. 至于什么是较好的质量, 评价并不唯一, 所以一个逆向的考察指标是,不捅娄子
+ 问不倒. 对整个系统从架构到细节, 当前方案选取的原因,都胸有成足
+ 视野. 对项目涉及的技术领域, 有业界眼光, 不局限于团队内的技术方案

我个人的倾向是:

+ 项目使用到的技术路线上, 有寻求更好的解决方案的态度和实际产出
+ 需要涉及到切换技术栈, 快速转换, 拥抱新的变化

至于考核结果是否以及如何同薪酬挂钩?  
我觉得应该挂钩.
应该分名利两部分: 
在虚拟的好处, 比如职级或者荣誉上激励;
薪酬方面的鼓励占一部分. 
毕竟, 有很多情况是没法用单一的评价体系的.

二  
知识管理问题的讨论
大妈的观点: 知识管理不是为了输出, 比如写博客材料, 或者演讲准备. 也就是目的性不能太强. 真正起到的作用是, 放纵自己的好奇心与求知欲. 在这个过程中, 积累散落各处的珍珠, 最后某一天用线把他们串起来, 组成属于自己的独一无二的项链.

<罗辑思维>这样的节目卖的是求知安慰剂.
知识管理也同样是一剂药, 但要求学员具有更多的主动性. 药的作用如何, 要看实际的知识管理课程具体的内容了.

**Comment by dadago2015** [comment]
## 一、小团队如何评估成长引发思
* 为什么提出这个问题
   * 传统KPI考核不适用于创业团体（小团体），当企业业务成熟，各部门稳定，权责明确，创新风险小，业绩容易以数字量化，适用于KPI；
   * 创业团体（小团体），不确定因素高，岗位界限不明晰，更注重成员的创造力，也更注重成员的成长，呆板的KPI不适用。
   * 保持知识型团队氛围
* 解决思路
  * 简单、明晰、一视同仁、公正的考评标准
  * 注重比较个体的自我成长
* 具体标准
  * 具体工作时效、质量、协作
  * 分享知识的主动意愿、频次、胜任力、业务关联性、时效影响（短期、长期）
  * 三个月（或六个月，时间段依据状况而定）考核一次
  * 优秀者当任某项任务的领头人，计薪酬   
 
## 二、对知识管理思考
* 懂知识管理者的“气质”
   * 善立计划
   * 旺盛好奇心
   * 有意识收集
   * 高效转化成果
   * 注重证据
   * 注重溯源

**Comment by yondjune** [comment]
wowo 杠杠滴~
:clap

**Comment by badboy315** [comment]
# GONGJIAN

## 纪要

### 1. 创业团队的成员成长评估方式问题

- 好的提问需要深入准备，当面交流才能更加深入
- 评估是个「伪命题」，评估是微言大义是为了什么？ 目的是什么？ 
- 无论是主观还是客观，都不是客观，客观的关键不是文档，而是人
- 外在动机的解决会带来无数个更多问题，而内在动机就是一台不停歇的发动机
- 解决问题思路：提出-思考-假设-验证-措施-检查-复盘-归档-复用，PDCA 的细分
- 成长的速度 换一种思路，分享、20%非时间研究、更多内在动机，都在成长的加速度
- 最好的程序员几乎都能清晰表达的思路，且爱分享。应了那句，教是最好的学。
	- 可是最 TOP 无法学，是应该模仿还不够，没到 TOP

### 2. PyCon2016China

- Pycon2016 民间组织，越来越有钱了，今天不用门票费；
- 更多是技术专题的分享；
- 和人介绍也需要不断迭代，是什么，为什么，各种角色如何参与？
- 开智的介绍，每人心中都不一样。一句话的力量 => 重要 	
### 3. OMKP

- 是要「果」，还是先「结」。大妈是从小到大的习惯导致
- 知识管理重要吗？ 有没有的区别是什么？ 表面来看，博闻强识
- 不断的收集 也是 一种 style，每个的方式也不一样，区别就在这，在自由化程度高的地方，才能区别
- 知道是不是能做到，也是 关键。到肌肉 更漫长。。。 存入内存调取远远高于硬盘。每个人的内容是不是有部自己的圣经

## 专题: 初创如何加速程序员成长

### 目标是什么？

相同时间加速度 ... 最好能有变成超跑

### 维度是什么？

传统我们知道有 制度、文化、物质、人心、环境 等各种因素。可是 排序 来看。先内部动机再外部动机。没有外部的，容易成为鸡汤。

- 分享加速
- 成果加速
- 迭代加速

是所以三个加速

- 分享加速 => 写+说，形成自己的关注，乃至影响圈。专注于核，内驱；
- 成果加速 => 团队作战，战壕兄弟，如何向 湘北 学习，有方法，有补位，有创新，能一起冲；
- 迭代加速 => 凡是定下就是反复，不能定下才能迭代。代代相传的加速度才是真速度。复盘 => 复用的加速，就是老美的套路；

是所以来说

1. 关键人 带起来 => 分享
2. 关键事 走起来 => Team 悦喜
3. 关键法 滚起来 => 不变维变

### 实施是什么？

1. ...
2. ...
3. ...

你眼中的行动是什么？

**Comment by ivanlau** [comment]
C2T2回顾

# 1. 初创团队/小团队管理相关话题


## 如何让成员保持成长/如何考核？

弓箭提到

- 结合技术领导人的主观管理和定期制度考核是否合适？

free提到

- 年纪比较大的程序员如何管理？

Dama提到

 - 关注成长
   - 和自己比成长的速度和程度
 - 关注分享
   - 通过分享考察成长
 - 提供公平公开的指标
   - 主观可以量化为公开的kpi



## 思考

- 考核
 - 对于管理人员懂技术的情况下，领导人主观判断比较合适。
 - 小团队只要有公平的评价体系、大家认同就可以。
- 成长
 - 根据具体行业/岗位/技术特点制定考察的个人成长坐标（如何量化？不同领域之间横向的学习、对技术纵向的深入学习）
 - 可以参考大公司的制度，取有效的部分
 - 通过分享的内容/量/变化来评定个人发展速度
 - 鼓励分享，提供分享机会


# 2. Pycon2016China 深圳场

- 议题和内容是否能有所改变和创新？
- 大家都多贡献力量

# 3.个人知识管理

- 知识作为资源，管理和使用可以参考其他资源管理的思路
- 知识管理也需要考虑成本和效益（包括边际）
- 应该思考知识管理选择容器？方式？内容？
- 实际上看起来大家收集的数据都很庞大，但真正使用的效果如何？
- 善于知识管理的人是否有一些特别可描述的气质？是不是从这个角度能反推如何有效的进行个人知识管理？

**Comment by badboy315** [comment]
按时关闭 ...

参与 8 人，按时提交 5 人。。。

**Comment by bambooom** [comment]
想到一个小点, 知识管理不仅是存储, 更是提取. 
在任何时候, 迅速定位并提取出来用才是正经事吧~~
