### ISSUE TITLE
7.30[C2T2bj] DAMA帝都闪聚

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/PRD#23]
## 是也乎

- 160730 20:30~23:30
- 列席: 15 人
- 自述录音: https://yunpan.cn/c6LZudpUSSkin （提取码：6e42）
- 命题作业:
    + 48小时以内
    + 各自回复 Issue 给出本次聚会的记要
    + 试分析: `人类社会进入宇航时代后,必然回归母系社会结构`

### 决议:

- 深深需要: 86年, 聪明, 有颜值 的男友
- 小闪需要: 稳定运营3+年的技术型社区创始人 作男友。期待的特质：
	- 工作之外有自主发起、折腾的事情
	- 能带着一群人一起玩儿，且持续改进玩法、玩得持久
	- 懂技术，开源气质
- 班长需要: 高效的接触我兰, 并变成老父的策略/渠道/创意

**Comment by CaosBad** [comment]
昨天晚上也尝试着讨论了一下这个话题，不过都没能够达成共识，而且参与讨论的人在概念上把母权社会和母系社会的概念混淆了。

Google 了一下发现已经有人在思考这个问题了。

[人类真的有过“母系社会”吗？](http://blog.sina.com.cn/s/blog_4b8bd1450102v2ub.html)

如果看过这篇文章可能就能明白人类在什么情况下会满足形成母系社会的状态。

- 食物充足，不需要依靠雄性或磁性任一方的能力获取生存资源
- 亲自不确定性变高，当男人无法确认自己的亲生孩子身份，母亲却能确定自己的孩子身份（有人质疑试管婴儿或体外培养，显然从生殖的角度来讲，确认母亲比确认父亲的难度要小很多。）
- 近亲繁殖问题，避免该问题的原因有三
  - 不和与自己出生于同一群体的异性交配
  - 性成熟后离开出生群体并加入其他群体
  - 不与性伙伴的子女交配；

那么宇航时代能够满足这几个状况么？

**Comment by bambooom** [comment]
wiki 上面说 
> 母系制度系指涉子嗣对母方家族的严格继承，并非是父系制度的相对概念。与常见的误解不同，母性制度不必然产生女权高于男权的情况

well, 我的想法是, 母系社会产生的条件之一是对于谁是父亲并不 care, 并且繁衍生育是种族生存中优先级最高的事项, 毕竟这是男性和女性最重要的区别. 假设到了宇航时代, 男性和女性的生理特征还没有变异成别的样子的话.....

然后, 我的脑洞是这样的. 
假设星际旅行成为可能, 但是大批量移民还未实现的时候, 对于新的星球, 必须有一批先驱者去开拓. 那么与其花费高额成本培训男性宇航员, 不如同样成本更多培训女性宇航员, 让她们带着优质精子直接前往新的星球进行繁殖或者在路途中生育, 反正一般要花很长时间才能抵达. (如果warp还没实现的话) 这种情况下, 大概会出现母系社会, 毕竟在什么都没有的新世界, 繁衍后代成为生产力是最重要的事. 
在新星球成为可以大批量容纳新移民的家园之前, 社会形态是如何决定, 如何变动? 又, 如果科技非常高级, 大批量传送直接成为现实, 先驱者们不必考虑运输成本和时间, 这种情况下还会有母系社会? Or, 生理特征真的变异了, 男性也可以繁衍后代的话呢? Or, 生育后代并不需要女性了呢, 这个叫体外繁殖? 

读书少, 脑洞不够用.... `_(:」∠)_`

**Comment by YixuanFranco** [comment]
嗷, 我也只说脑洞了昂. 

### 背景: 姓与氏
姓氏直接代表你的血缘, 家族什么的的. "姓" 以女字为偏旁部首,   
其实最早并不代表父姓. 而是母姓, 子女随着母姓更改.   
氏是姓之后出现的...可以代表父亲的姓, 可以代表所处封地...  
然后, 后来的`氏`取代了`姓`变成现在的姓.  
**以上是背景**  

### 所以...我猜...

* 寻祖: 资源不稳的时候, 人要稳定的 "追根大法".    
  * 毕竟, 在这个社会结构相对稳定的情况下, 很很容易玩出父不详的情况. 子宫还是长在女性身上, 各大星球混杂时, 女性想和谁玩, 机会成本不会那么大了, 大家都变成 high mover, 那么, 认妈比较保险...不容易出错.   
  * 生殖: XX+XY, 哪个胆大说的....? 如果 Y 本身不重要了...女性本身能自繁殖, 那玩法就更多啦. 男性的低生殖成本 VS. 女性的高生殖成本...导致女性要么越来越挑剔, 要么越来越有谈判成本, 男性为了赢得生殖权, 可能需要有所牺牲, 具体牺牲是啥...可能是金钱, 可能是资源, 可能是权力...可能是姓.
  * 肉体满足: `一个男人可以让十个女人怀孕, 但十个男人都不一定能让一个女人满足.` 是也乎...男性很多身体配置都不够女性玩啊...现在女性已经慢慢开始消费男性的脸了...虽然各大直男一直很不愿意接受女性评断, 但这玩意儿就是一个趋势. 以后会慢慢开始消费男性性能力吧...毕竟大清亡了一百来年了, 宋儒的脑残游戏规则人也忘的差不多了...
  * 观念替代: `有时候不是新的观念取代了就得观念, 而是持有旧观念的人, 都死光了`: 当前 50s 60s... 可能是带着完整贞操观念最后一代了...70s 80s 是半感染代, 90s 00s 是崛起代...只要等前人都死光了...世界就安宁了....大家可以提前进入 freedom 回归母系时代.
  * 束缚: 这篇我已经辩述过了, 戳→[贞操观](https://www.douban.com/note/236996292/)
  * 恶性攻击: 戳→ [如何毁掉一个人](http://yixuan.li/trivial/2015/12/10/howToDestroy/)

**Comment by CaosBad** [comment]
> 一个男人可以让十个女人怀孕, 但十个男人都不一定能让一个女人满足.

这个结论咋得出的？ @YixuanFranco

**Comment by YixuanFranco** [comment]
@CaosBad 这是一句英文. 我前男友说的. 具体的英文原文我也不知道...因为他是翻译过来说的...

**Comment by ZoomQuiet** [comment]
## 160802 DAMA
~ 嗯哼, 第42小时的回顾

- 15人的场子, 按时提交作业的有3位, 其中两位 MM, 怪不得未来一定是母系的呢...
- 其实, 这个问题的提出也只是因为现场 1/3 的MM 主导了话题走向激发出来的
- 问题: `人类社会进入宇航时代后,必然回归母系社会结构`
- 其实就是一个对可发展型三观的检验:
    + 男的, 直接先质疑 `母系社会` 的真伪
    + MM 都在思考 `宇航时代` 社会结构的变化可能
    + 这其实就是经典的 僵固型vs发展型 思维面对问题的思考模式差异哪
- SiFi 都看过, 其创作的 `软/硬` 之争一直有, 但是,真正着手写就知道,其实没有什么差异的
    + 都是要从一个不可能的假设开始,用科学的推理完成整个儿世界的构建,再配合上感人的故事
    + 只是科学的推导偏向技术还是社会而已
- 竹子的思考方向, 其实是20年前的一个中国原创 SiFi 的大纲: `文明种子`
    + 只携带受精卵的小型殖民飞船
    + 标准殖民流程是自动航行到合适的星球
    + 降落后,先制造最小生活空间,然后人工子宫生殖出一对男女
    + 用家政机器人养育长大,成为首代领导人, 决定后续的发展策略
    + 但是,在无数种子飞船宇航过程中, 有各种意外, 也慢慢导致衍生出了各种类人社会,甚至于异人类...
- 所以, `人类社会进入宇航时代后,必然回归母系社会结构` 问题本身是开放的,
    + 也并没有规定是思考宇航群体,还是地球母星社会结构
    + 关键就是看大家是否愿意从一个假设开始,如何,以及能思考多少层次的变化
    + 以便脑补到完备率百分之多少的全新世界...
- 当然, 按照俺习惯的三三制思考结构能规范思考的方向,以免想乱:
    + 宇航时代前:
        * 大规模准备宇航:  
            - 发达国家进入
            - 主要国家加入
            - 全体加入
        * 大规模进行宇航
            - 精英阶层接受
            - 中层主力接受
            - 下层被迫接受
        * 大规模抵制宇航
            - ...
    + 宇航时代中:
        * 初期:
            - 各种意外/失败导致的社会迭代
        * 中期
            - 各种成果引发的势力竞合
        * 后期
            - 母星保护主意抬头的后果
            - ...
    + 宇航时代后
        * ...
- 时代背景有了精确设定后, 从大家容易接受的生殖/资源/管理 等几个主要方面进行进一步假设
    + 就能不断获得好玩的结论
    + 再配合上想象力, 就能收获有关母系社会这一框架中的各种变化


整体上, 这其实就是一次编程思维的练习而已 ;-)


DONE as good! 达成/归档/交付ed

**Comment by badboy315** [comment]
录音只有 单身/非单身 介绍 ... 

亦然听到了单身男女的`渴望`和非单身男女的`满足`

> 15人的场子, 按时提交作业的有3位, 其中两位 MM, 怪不得未来一定是母系的呢...

嗯哼.
