### ISSUE TITLE
[SZC2T2]8.9 七夕 记要

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/PRD#24]
## 邻海

录音: [160809C2T2sz/](http://openmindclub.qiniucdn.com/res/tapes/omprd/160809C2T2sz)

### 诗曰

    天上七夕架雀桥
    深圳是夜大妈聚
    牛郎忍年会织女
    桃园开智为牙祭
    另有妙竹自西来
    一探家乡可爱郎
    反正任性这夏夜
    深广珠江就美食
     RAmen 是也乎
    ╮(╯▽╰)╭ 

遇雨:

    地铁三匝, 何枝可依
    山不厌高, 海不厌深
    大妈吐哺, 深圳归心
    海鲜合蒸, 俺已饿了

### 作业

`妙竹` 在深圳期间

- 至少发动一次 C2T2~
- 和 @巧玉 致少一次 SPA~

此之为定向作业~

**Comment by Langzzx** [comment]
## 只为见大妈

>七夕觐大妈，
>米粥蒸海鲜。
>杜克女学霸，
>八卦NaAgo。
>饮酒谈恋爱，
>不负老杜康。
>立体环绕声，
>谢辉赠好书。

不记得有大妈，可称小鲜肉，因为辫子没了。

**Comment by ivanlau** [comment]
终于见识势如妙竹，
抓住机会现场科普，
于我如灌顶之醍醐，
提了问获得答有如：
基因是否为宿命谱？
了解更多更能造福。
药物审批流程何如？
会后甩高质量科普。

大妈话题依然丰富，
天南地北人情世故，
从大西北到数据库，
从程序员特别之处，
谈到他们待人接物，
如黑客与画家感悟，
大妈果真老司机（司机划掉）师傅。

要想知道有多cool，快来参加C2T2！

**Comment by ZoomQuiet** [comment]
DONE as good! 达成/归档/交付ed
