### ISSUE TITLE
OMPRD广州[C2T2]+2 纪要

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/PRD#3]
# 7.9[C2T2]OMPRD广州第二次集会纪要

- 时间: 150709 19:42~21:12
- 地点: https://github.com/OpenMindClub/PRD/wiki/EventC2T2
- 内容:
    - 自我介绍
    - 现场代码
    - 其它现场
- 150709 12:21 前, 能来参加的智友
    - 说明想分享什么内容
- 注意:
    - 到时,少于 5 人的话
    - 自然流散本次 C2T2 线下小聚
- 参会人：大妈 晓枫 anna 刘伞伞 刘果林
- 发起人: 大妈
    + [7.9[C2T2]广州 二次召唤 - Google 网上论坛](https://groups.google.com/forum/#!topic/omprd/wqOCSP2_k10)

**Comment by ZoomQuiet** [comment]
- 记录人：刘伞伞

会议核心议程：

1.主题分享

2.现场编程

3.自由讨论


###暖场&参会目的

大妈：上次只有两个人，这次开始最少5个人，介绍“我是谁 从哪儿来” ，希望能每周进行，四次以后大家自己走起来。大妈这次做主持＋现场展示。

晓枫：分享一下进入开智后的心态改变。

anna：体验一下编程生活。

刘伞伞：过来感受一下气氛，跟上大家的速度。

晓枫：带来了主题分享：《小巷世界》的构思。

###主题分享
晓枫：《慢可能比快要好》
>同辈压力同辈信任很重要，但也要有自己的节奏。
>
>受到开智群智力碾压后很焦急。但现在懂得人的精力有限，应要找到自己的兴趣。女友的支持和鼓励起了关键作用。现在进行的是会自己做记录，会跑步。


大妈点评：

>对晓枫的演讲技巧进行点评。以安替老师的演讲作为案例，提出演讲应该“重复”和“总结” 技巧。
>
>内容：这个演讲提到1.关注自己的情绪加以调节 2.开始跑步。演讲时提到“学习跟不上”是伪命题。你以为看了书就学到知识是不可能的。十年以上的积累才能“学会”一个东西［坑1］。
>
>你是不是真的知道自己要什么。解决方法：1.知道我要什么 2.什么都去尝试。开智给了一个“广泛的可能”。但重要但还是自己去读，去反馈。
>
>魔都帝都生活节奏快，深圳和珠海也都有联合创新者，但广州还没有［坑2］
>
>学习最爽的方法是：昨天学的今天抛出来。


果林：《小巷世界》
>《小巷世界》是对自己生活缩影
>
>旧书摊的引申
>
>设想一：一个小巷套着另一个小巷 
>
>设想二：不同形态的小巷毗邻 在外力作用下主角进入不同小巷
>
>  三个主角：混混 智者 观察者
> 
> ……

大妈点评
>果林的描述缺乏最小故事结构。 举例：阳老每次漏出的东西是结构完备的。
>
>两段演讲都应该先说清楚今天想干什么。果林的描述缺乏目的性。以后人多的话演讲时间缩短，要有说清楚自己目的的能力，抓住听众注意力。
>
>碎片化信息导致对书的感觉十分重要 

>现实性写作需要对角色的理解，如果果林不了解主角的生活，就无法写出好故事。虚构写作要基于非虚构生活。
>
>果林要开始行动，开始写。［坑3］


###现场编程
大妈演示了42分钟的编程并给出命题：看看大妈用Mac的习惯有何不同，给anna和伞伞每人五分钟安利Mac。

anna：1.速度 2.人性化

伞伞：1.速度 2.人性化 3.界面干净 4.操作便利

大妈点评:

>两个人安利的时候都直接给结论，但故事最打动人，所以要给故事。
>
>都没有提到mac可以不用关机
>
>Mac结合win的应用性和linux的高效率
>
>如何发挥机器的极限：妹子们1w的机器只用了500元的作用
>
>写一些从win到Mac有什么不同［坑4］


###自由讨论
####1.每周强制输出
大妈：每个人今天听到的重点不同，获得了什么，都写一份记录［坑5］。强制性输出的东西是什么？

#####［大妈给的被动压力］[每个人的坑6]

果林：写小巷世界

晓枫：给大家展示写作班中自己得意的作品

anna：编程帮助管理

伞伞：编程帮忙找到前沿研究领域的信息（文献或链接）

另：大妈提到：为私人问题去学习：大妈对编程和专业进行分析。提出命题越小、越个性，就越值得解决，做一个MVP。python只有23个关键字，完全可以学。大家在开智得到的都是结论性的东西，但是大家get后要去用，才会变成自己的能力。

####2. 执行意志的管理

伞伞提问：为什么我先做琐碎的事情，不做重要的事情

大妈：为什么先做低价值的东西，不做高价值的东西？
1.觉得重要的事情难 
想做好重要的事情，但重要但事情谁新的事情，难是自己想出来的，不是真的难，只是没经验。

处理方法：a.不要吓唬自己 b.不要宏大目标性质，只下行动指令。把大事拆分成小事。如25分钟写300字。

2.低价值的事情更容易带来成就感
低价值的东西更容易带来成就感，成就感来自于自己给自己的满足感。琐碎的事情容易有成就感 比如倒垃圾。所以反馈快，成就感获得快。

处理方法：拆分大事。能一刻钟获得一个成就感（番茄工作法的优势）
 
大妈：从幼儿园开始都是用 目标式。但大脑就是为了执行命令，而不是为了思考目标

果林推荐书籍：《成功：动机与目标》


（今天先写出全部重点，再找时间写故事性个人重点）

**Comment by ZoomQuiet** [comment]
~ 书记员: 晓璇

# part1.自我介绍
# part2.主题分享

（1）晓枫：关于自己的改变
深圳聚会之后，自己思想上和行动上有所变化。思想上，第一，关注自己内心想要的，去专注他，不被太多杂碎的事情干扰。第二，以一种轻松的心态去学习，例如写作课，在女友的鼓励下，不会因为自己不擅长就回避它，只要比之前的自己有进步就行了。行动上，第一，坚持每天记录5:50-10:30自己的活动项目以及每天的花销。第二，坚持早上5：50跑步，一周六天。

大妈开光： 从演讲和内容两方面进行点评。

演讲方面，演讲里最重要的一点是“重复”，虽然你思维比较乱，但也有下意识去做，问题是讲完后没有总结。安替老师在演讲的时候，最后就会总结：我今天主要讲了三点，第一，第二，第三。

内容方面，你感觉自己在开智群被碾压，大量知识跟不上，其实是个伪命题。信息压力的处理我们已经有将近20年的经验，小学初中高中的信息压力不会比现在的少，问题是上了大学之后，就把这种处理方法忘光了。是自己把自己给拖累了。还有一个坑就是，你以为在开智群看了他们推荐的那些书就是学到了，其实那是不可能的，知识不是这样学到的，如果是这样，那搞科研就太easy了，像安替他们能成体系地介绍或者写成书的，至少是三年，平均来说十年以上的积累才有。你想在一个月之内学会任何一项，不可能。所以你说的这种学，是一个极其错误的自我定位，这是很大一个坑。另外说到自己要什么，也是一种伪命题。想要什么，一种是自己觉得想要，一直坚持，就变成自己想要的，另一种就是自己广泛去尝试，360行每行都去尝试，倒霉是我们没法活那么长。加入开智群的好处就是很多领域的大牛能给你指明道路。我觉得你所说的最大的改变是：习惯了。习惯了开智的一种虚拟的碾压。为什么要组织线下的活动——被动进步，我们要营造一种环境，施压让参与者有所输出，有所进步。学习的最好的方式就是现学现卖，这是最爽的。

（2）果林：《小巷世界》的创作想法

大妈点评：两个问题：第一，跟上次的问题一样还是想得多做得少；第二，所分享主题思路还不够清晰，主题目标换了四次，不知道要表达什么。演讲时间有限的情况下，一定要明确好自己讲什么。另外要思考的问题是怎么证明自己是爱看书的？

# part3.编程演示
大妈通过微信公众号查找文章作为例子给我们演示。在演示过程中出现了bug，大妈几乎整个过程就是在找问题所在。虽然整个过程我都没看懂为什么要这样操作，但也算是见识到了程序员日常工作中的一个常见的状态，就是不断查错和反复测试。看着大妈在演示，感觉编程有以下几点必不可少的：（1）很强的逻辑思维能力；（2）认真严谨的态度；（3）极大的耐心；（4）良好的英语基础。

# part4.问题讨论
（1）mac和其他自己之前使用过的电脑有什么区别？

大妈开光：
A.故事是最容易打动别人的。你们说的很多都是结论性的东西。“快”这个特点你们都没有说到点子上，不用开关机，秒开，这个就很有说服力。B.怎样发挥机器的极限，是自己说了算。比如一台机器是一万元，但是自己只用了500块钱的功能，就很亏。C.可以尝试去写“为什么用Mac”的文章，通过写作自己才会更多去思考。D.当面交流，持续不断地即兴演讲的好处就是立马能得到反馈，通过演讲可以很快看出这个人是不是有积累，说话是不是有条理，有感染性。

（2）每周花几个小时来参加这个活动， 应该获得什么？

大妈开光：A.谁主张，谁执行。现学现卖时最好的。晓枫可以分享一下自己在写作班最得意的作品，强制输出，这样一周一周下来，就很容易看到你的进步。B.Anna和刘伞伞想要学习编程，核心的学习方法，应该是找到自己的兴趣，通过编程去连接它，而不是学习了编程才去做。为我的私人问题去学习，这样才有目的。C.开智群里有很多干货，但那都是结论性的东西。这些结论是怎么来的，不知道，只把结论记下来，没用。知识和能力是两岔儿的，知识必需通过自己的学习练习变成自己的能力，才能解决问题。否则，除非你遇到的情景和所学的案例一模一样，你才有可能用得上。知道那么多结论性的东西，但是不去用，就永远不会是你的东西。

（3）解惑：明明是重要的事，为什么会做不好甚至没有做？

大妈开光：A.不愿意做难的事情,其实涉及到执行意志的管理。比如说，八点了，我要干什么，要给自己明确的指令。千万不要说，八点了，我要做完什么。不要下目的性的指令，要下具体行动的指令。B.压力永远只来源于自己。难的事情是自己被自己吓到的，不是本身真的难，有可能是经验不足或者其他。重要的事情不要想的那么重要，拆分成具体的任务来完成就不难。总的来说就是处理好两件事：1.不要自己吓自己；2.不要下目的性的指令，而要下具体行动的指令。

# 个人感悟
1.这样的线下活动对人的改变确实是最直接也是最有效的。在开智群里，常常接受大量的各种各样的信息，但像大妈说的，那些都是虚拟的碾压，看到那么多的信息真的对自己产生很大改变吗？不见得的。而我们的线下集会要求我们有输入，然后将输出分享给小伙伴们，同辈压力会强制自己有定期的输出，进步就会更快！

2.回来听录音发现自己的表达还是很差劲的……各种思路不清晰，说话不连贯，用词不准确，真是无力吐槽自己-_-#不过既然决定要有输出，就会给自己施压好好改进，希望不久后能看到不一样的自己！各位，共勉～

**Comment by ZoomQuiet** [comment]
**书记: 晓枫**

### 自我介绍 （每人约1分钟） ###
主要内容：  
- 你是谁  
- 来自哪、到集会地点所花时间  
- 参与集会主要目的  
eg:我是大妈，来自猎豹移动，主要目的是主持集会和现场编程开发演示  
### 主题分享 （每人15分钟） 
- 晓枫：参加开智5.26线下深圳聚会后所做的改变  
- 刘国林：个人写作实践：《小巷世界》  
- 大妈对两位同学的分享进行点评  
### 现场编程演示 （42分钟）
- 问题1、为什么编程人员喜欢使用mac。  
- 问题2、从编程演示：观察windows与mac系统区别。  
- anna和刘闪闪每人5分钟安利mac。  
- 大妈安利mac及点评  
### 自由讨论   
- 完善广州定期线下活动。    
- 如何让自己从此次活动中受益。  
- 编程核心学习方法：将周边最密切的事物与编程联系起来，先去做，再去解决问题。    
- 执行意志管理  
### 个人所得  
- 即兴演讲最重要的是有一个核心故事，抓住听众注意力，故事是最容易打动人的。  
- 能现学现卖才是最有效的学习。你能输出多少，就是你所学到的；并不是你看了很多书，知道了很多理论，就学到了很多。你在开智所学到的东西，要去运用它，去解决问题，才是你所获得的能力。这一结论浇醒了还在迷失的我。  
- 你所用的操作系统，会潜移默化的影响你的思维。   
- 对于问题思考，可先从数据进行基础分析，review数据，发现关键所在。eg:为什么无法完成写作班作业。   
- 知行合一，行动最重要。行动困难，是由于给自己下达目的性指令（eg:我今天要把写作课作业写完），而不是具体行动性指令（eg:我今天写一些文字）。从最小的事情开始切入，从自己的当下，并不是为了未来，而是为自己的私人问题去学习。  
- 对于问题思考，可先从数据进行基础分析，review数据，发现关键所在。  
- 通过C2T2这种活动形式的确是可以倒逼自己的输出能力。

**Comment by benafrant** [comment]
记录人 ：刘果林

 

## 缘起

经过上一次review的反思和总结，这一次的召集会大妈提前两天在开智群发布通知，并且给群友发了邮件，并且增加了条件：1.写好想要分享什么内容；2.不少于五人报名，否则召集会自然流散。截止7月9日近五点，终于确定有五名广州群友报名，使得第二次召集会才得以继续。地址依旧是广州市珠江新城富力盈通大厦3110会议室。时间19:42-22:07。

 

会议核心议程：

19:42 ~ 20:24
intro. Self

20:26 ~ 21:08
coding show

21:08 ~ 22:07
discuss chaos

 

## 会议过程

 

### 与会人员

大妈

晓枫

Anna

刘伞伞

刘果林

 

### intro. Self+内容分享

在简短的介绍之后，晓枫首先分享演讲“慢比快好”，讲诉了在开智群接受碾压之后所带来的改变，接着刘果林分享了写作实践计划“小巷世界”，讲诉关于小巷世界的细节和目前的进展。针对每一个分享，大妈都会进行点评：

>*    演讲长短和演讲的思路的清晰没有任何关系，晓枫的演讲只用了不到5分钟，果林的演讲则用了13分钟，但是两个人的演讲完全听不出一个明确的目的。
*      而像安替老师的演讲，他会在演讲中总结自己的目的，最后告诉大家，他讲的就是这么几件事。
*      5分钟、50分钟、甚至5小时的演讲，只要能牢牢抓住听众的注意力，这也是一种写作能力。

 

>关于“小巷世界”的批评：
*    还是只是停留在一个世界观和意象的环节，没有去进行写作实践，没有故事，而且在听了你的讲诉之后都没有想要去看的欲望，而且整个演讲慢慢变成了你的自言自语。
*    在演讲开始提到的旧书店消亡的现状倒是可以表现现代人的读书状况，值得尝试。
*    非虚构写作和虚构写作并没有界限，如果你没有经历过，那么你写出来的东西就没有说服力。(推荐阅读常书欣《黑锅》)
*    读书太少，你如何证明自己喜欢读书？想当然和实际出成果是有相当大的差距的。

 

### coding show

大妈本次的编程任务是完成使用一个微信后台控制两个微信号的编程工作，费时42分钟，完成关键步骤，找到关键问题。

 

在大妈演示了编程生活之后，向同使用苹果笔记本的Anna和伞伞提问苹果笔记本相较其他系统的笔记本的好处在哪里？如果向别人推荐买苹果笔记本，如何让别人心动，愿意投资在苹果笔记本上？

>*    故事是最能打动人的。
*    写一篇技术性的文章，这样既可以在向别人表述苹果的好处时理清楚线索，又能促进你进一步了解使用苹果笔记本，挖掘更多的价值，而不是处在花了8000元只用了800块的功能的现状。

 

### review

 

 

>*    谁主张，谁执行。每个人要利用压力迫使自己做一些事情。每个人承诺每个星期输出的东西，找准方向。
*    大妈学习编程的核心学习方法：先去做，找到自己的兴趣，先尝试去解决，中间遇到困难，公开来解决。编程和写作的训练就是思维的修炼。
*    知识和能力的区分，只有将知识转化为能力，才能解决问题。知识永远不用，你的能力将永远受禁锢。
 

## 个人感悟

 

>*    转化思维
在大家一起聊如何开始行动，不拖延的时候，大妈提到我们没有养成“是什么”思维的习惯，而是“为什么”的思维占据了主导，很大原因是中国一直以来的教育是以宏观叙事为主，比如“为中华之崛起而读书”，那么我要如何从宏观叙事的教育思维里逃脱？我的解决方法是自学：在观察反思中自学。
*    现学现卖
将所学到的东西展示出来，用成就促进自己前行，实践带来反馈。
*   养成review的习惯，可以在日常学习中，完成一段学习任务，最后进行eview，利用思维导图整理思路。

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
C2T2 的核心是现场编程,但是,大家对现场编程的体验重点完全不同,
这也是引发我们必须思考的一个基点: 如果在相同的环境中,跟上思路?

另外,这种基于 Discuss 的记要形式,有什么好处,问题,技巧,,,

也是要在坚持体验中才能体会到的,
那么下周再见 ;-)
