### ISSUE TITLE
OMPRD广州[C2T2]+4

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/PRD#5]
OMPRD广州[C2T2]+4

## 简介

2015年7月16日  19:00-21:00
记录人：陈素封
参与人员：大妈和陈素封
地点：富力盈通大厦、花城广场和火锅店
活动定义：非常规活动的常规活动

>非常规是指本来这次[C2T2]+4活动不足五人应该流散，后转成FB，结果发现FB出了一些有价值的内容，最终变成[C2T2]+4

## 签到图

![2025932348.jpg](http://upload-images.jianshu.io/upload_images/32598-47e320db6cc0cd5b.jpg)

为什么没有大妈？大妈说用衣服来签到，这怎么能行？

于是，补一张。

![188981235.jpg](http://upload-images.jianshu.io/upload_images/32598-d2094c817435721f.jpg)

## 设备清单

大妈带领参观猎豹移动，发现全公司就发现他一个人的工作台是在用苹果，晒大妈工作台一张，GEB镇台。

![2120359009.jpg](http://upload-images.jianshu.io/upload_images/32598-d712eebbfabe3d4d.jpg)

### 固定设备

- ·MacBook Pro (15-inch, Late 2011)，升级到 10.10，内存只有 8G，没有去光盘加 SSD
- ·DisplayLink 兼容 USB 显卡，形成一拖二、三屏工作环境
- DELL E177FP 负责 1024768 标准幅面排版测试
- DELL U2212HM 12801920 竖屏 CLI + 文档
- ·FILCO MINILA 青轴 ~ 替代 HHKB lite2 (用了 5年)
- ·WACOM INTUOS pen small ~ 替代鼠标
- ·actto 杂牌支架
- ·microlab 4.1 有源音箱 （用了超过 8年）
- ·AKG K99 耳机c

### 移动设备

- ·SAMSUNG note2 移动协约机 +16G SD 扩展空间，作为主力联系平台
- ·iPhone 5c USA 裸机行货，作为主力摄影 / 支付中心，不配 SIM 卡，纯 Wi-Fi 使用
- ·SAMSUNG T310 + 32G SD 扩展空间，作为移动媒体中心
- ·Kindle Paperwhite 一代，作为主力阅读平台
- ·SANYOICR-B001M 录音笔 ~ 进行客观记录
- ·小米电池 10400ma
- ·TP-LINK WR702n mini AP ~ 用来替代酒店的样子 Wi-Fi

### 桌面上的书

- G 术图书：14 Gödel,Escher,Bach~集异璧之大成
- G 术图书：12 传家 中国人的生活智慧
- G 术图书：17哲学家们都干了些什么?

[数据来源](http://segmentfault.com/a/1190000002602360)

### 为啥上市的科技公司不都是用mac？
- 省钱
- 考虑网络承载能力

### 猎豹移动

- 表面上是工具类公司，实际上是大数据公司
- 表面上看是离线工具，但是每次都要拖动大后台
- 竞争对手竟然不是国内或国际的工具清理类应用，是facebook！想不到呐！

- [参考资料一](http://money.163.com/15/0521/09/AQ4MJNQ300253K1O.html)
- [参考资料二](http://tech.qq.com/a/20150302/064028.htm)

### 开智讲座建议

- 每次对外的输出都应该规范、专业、系列
- 规范：参考CCTV春晚
- 专业：登记过的信息就不应该重复提供
- 系列：每次的讲座服从中心主题
- 为什么最近的讲座不如前期的好？具体翻看聊天记录中王佩和阳志平主持的讲座
- 每次开完讲座之后都应该对群内造成影响，这样会产生持续效果，不然就是纯分享

>补增[《个体学习、组织学习与学习型组织之辨析》](http://www.nssd.org/articles/article_detail.aspx?id=22680149)，应将开智建设成一个学习型组织，而不是组织学习的地方。
>
>学习型组织是学习发生的地方并且推动一个组织前进 ，学习必须在组织或组织间由个体学习向团体学习转化 ，必须导致行为的变化。假如它不导致行为的变化 ，真正 的转化就没有发生 。

### 聊天记录问题

- 为什么py班的同学没有提出要学保存群内聊天记录？大妈也表示不解，因为代码也已经开源在github中，为什么py一期结束后，还要安替来释出聊天记录？
- 其实安替保存的聊天记录是释出的最后一步，每天的聊天记录都会用邮件列表发布，没有翻看聊天记录的人就不会知道
- 曾经试用kindle推送群内聊天记录，技术已经达成
- 大妈的其中一部手机就是用来导出聊天记录，其中的微信也不敢升级，怕影响以前的聊天记录

### 社群信息分享

- 从远古生存到农业发展，从信件到网络微信，谈管理边界，社群将信息分享变得更加容易
- 利用微信来将时间源头理论的未来不分地域地拉平是一种创举
- 未来更应该将虚拟现实结合，将信息更好的共享
- 未来的开智课程应该是像足球直播一样令人振奋

### 珠三角Co

- 个人看法：大妈其实是宝矿
- 是不是大家把编程的标签往大妈身上贴呐？
- 我就不会编程，但是一样可以向大妈学习编程思维
- 其实以上谈论的东西也根本没有编程相关难理解的东西
- 再者，大妈对知识管理、编程以及道教也很有研究
- 建议大家留意看看大妈的博客以及zhgdg，几乎都可以深挖
- 嗯，大妈开光很有耐性，给大家安利大妈

### 补增大妈感动我的一件事

![image-2015-07-16-23-38.png](http://upload-images.jianshu.io/upload_images/32598-00cc3658fe228a15.png)

![image-2015-07-16-23-39.png](http://upload-images.jianshu.io/upload_images/32598-562e4156e6ff4f9d.png)

[截图来源](https://groups.google.com/forum/#!topic/python-cn/aCLB_IJC4uI)

##补增《面基之意义》

面基也可以理解成合作学习

- (1)明确的相互依赖(positive interdependence)，小组成员之问必须相互合作才能实现目标 ，这样将能确保合 作成员对最后取得结果具有较高的满意程度；
- (2)个体责任性 (individual accountablity)，小组里的所 有学生都有责任共享他们的工作，并且掌握所有要学习的材料 ；
- (3)面对面促进性交互 (face-to-face promotive interaction)，在合作学习中，部分工作可以平行进行或者个体单独完成的同时，也有一部分工作必须是小组成员在 一起 彼此互相评价、反馈意见、分析挑战，并且在此过程 中学会互相鼓励 和取长补短 ；
- (4)合作技巧的恰 当使用 (appropriate use of collaboratives kills) ，要鼓励学生并帮助他们发展和使用信任建立 、决策 、交流 、领导和冲突管理等多方面的技巧；
- (5)群体加工(group processing)，小组成员要共同完成一些加工，包括小组目标的设定，周期性评估他们作为一个整体工的进展，以及识别为了在未来更有效工作而要 进 行的变化等。

来源[《自主学习合作学习探究学习的实质及其关系》](http://www.nssd.org/articles/article_detail.aspx?id=40109737)，强烈推荐阅读

##迭代

- 2015年7月17日 00:46:27
- 2015年7月17日 00:50:26

**Comment by ZoomQuiet** [comment]
其实吧,应该如
OMPRD广州[C2T2]+2 纪要 · Issue #3 · OpenMindClub/PRD 
    https://github.com/OpenMindClub/PRD/issues/3
增补到:
OMPRD广州[C2T2]+3 · Issue #4 · OpenMindClub/PRD 
    https://github.com/OpenMindClub/PRD/issues/4
后面变成评注的哪,,,,

这样才吻合:以 github 为核心的高效协同沟通 
    https://github.com/OpenMindClub/PRD/issues/1
的建议,,,,

而且,这次,FB 是在 C2T2+3 的框架中进行的,,,
不是 +4 哪,,,

所以,俺先关闭之,你复制为 
OMPRD广州[C2T2]+3 · Issue #4 · OpenMindClub/PRD 
    https://github.com/OpenMindClub/PRD/issues/4
的评注的?
